# Netlify configuration for Manish Kumar Rajak Portfolio

[build]
  base = "frontend/"
  command = "yarn build"
  publish = "frontend/build"

[build.environment]
  NODE_VERSION = "20.9.0"
  YARN_VERSION = "1.22.19"
  NODE_ENV = "production"

# Redirect rules for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
