# Netlify configuration for Manish Kumar Rajak Portfolio

[build]
<<<<<<< HEAD
  base = "frontend/"
=======
  # Directory to change to before starting a build
  base = "frontend/"   # run install & build here
  command = "yarn build"
  publish = "build"
  
  # Directory that contains the deploy-ready HTML files and assets
>>>>>>> fa9625657fff845d9f98399671a5c6452da62408
  publish = "frontend/build"
  command = "yarn build"

[build.environment]
<<<<<<< HEAD
  NODE_VERSION = "20.9.0"
=======
  # Node.js version
  NODE_VERSION = "21"
  
  # Yarn version
>>>>>>> fa9625657fff845d9f98399671a5c6452da62408
  YARN_VERSION = "1.22.19"
  NODE_ENV = "production"

# Redirect rules for React Router (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/static/*"
  [headers.values]
<<<<<<< HEAD
    Cache-Control = "public, max-age=31536000, immutable"
=======
    Cache-Control = "public, max-age=31536000, immutable"

# Form handling (for contact form)
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.herokuapp.com/api/:splat"
  status = 200
  force = true

# Environment variables (these will be set in Netlify dashboard)
# REACT_APP_BACKEND_URL = "https://your-backend-url.herokuapp.com"
# REACT_APP_SITE_URL = "https://manishrajak.netlify.app"

# Build plugins (optional)
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Branch deploy settings
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
>>>>>>> fa9625657fff845d9f98399671a5c6452da62408
